before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: ioHiCT7wshn+tl6V0keLCybTFPfbiM+VlAv/hTUc5LnbaHyCvGQHdp6cf9zxhPTEThkTOnFGVVw8UNDrJUqxNXD7q+U7ARA+xSNobTb3b989TPH4lpa6d2WATzA8e9d+IDFv6mBVfAIESjtC+I/n/j6mJRZkdSc7GhCqMOmDvNNHHYhU2/0hJrKIGiNtFJ9o9GUMP++sc5mnPHQ5+5Yy2aC//Z5sHHK3uZVmiuGd6wkkdxM2eeaoqcaqYx/zU/cxeVI+cq6EcJy6Rv3UFUT2xvjm055ACH5L/ZnMzFkuuNGYEZ48m320P8QfqeGDrKPSujOCT/HAGgpOz9AKhsUE8dj0wEN955UfFrUywmhvH+rw9I2uMnYL1CBg+KzJDW/+NymD7DpeSoLNK7paOTmAf+nxpDJCKrCXdTbCSaq/xJEaKq+k1WdkFPsq8HmYHSQKpDe4jZfHrsxo9Gax6T+gnvZifpTu1gOzSNM8X3iUJoB0qLgU+CEbv4bpUP8bUfV1bkYTi+HCfvp6JE7hzB0yeRBcNp+d9k9m990OMdFaA+sGXtbENTatTe3JQxEoOKhJ0tbyUfyRNNUAW8GPxjn02t/sa4CXJp9GilizYH5Biefeva/6ob0PCMofn2pWbNh2LCnbwZbS0L2VsXVaq85C5035Q67etGmoBiQbOiQeNq8= # CRYPTO_AES_KEY
language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
